name: Build and Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build .NET
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ 'csharp' ]
    steps:
    - name: Checkout repository
      id: checkout_repo
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      id: init_codeql
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        queries: security-and-quality
    
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      id: analyze_codeql
      uses: github/codeql-action/analyze@v1