name: Main Flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

      
  syncSecurityAlerts:
      runs-on: ubuntu-latest
      steps:
        - name: "Sync security alerts to Jira issues"
          uses: reload/github-security-jira@v1.x
          env:
            GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
            JIRA_TOKEN: ${{ secrets.JiraApiToken }}
            JIRA_HOST: https://foo.atlassian.net
            JIRA_USER: henrique.santos@hurb.com
            JIRA_PROJECT: Infosec
            JIRA_ISSUE_TYPE: Security
            JIRA_WATCHERS: henrique.santos@hurb.com
            
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
