name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          6.0.x
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@preview
      id: msdo
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
        
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
      
  syncSecurityAlerts:
      runs-on: ubuntu-latest
      steps:
        - name: "Sync security alerts to Jira issues"
          uses: reload/github-security-jira@v1.x
          env:
            GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
            JIRA_TOKEN: ${{ secrets.JiraApiToken }}
            JIRA_HOST: https://foo.atlassian.net
            JIRA_USER: henrique.santos@hurb.com
            JIRA_PROJECT: Infosec
            JIRA_ISSUE_TYPE: Security
            JIRA_WATCHERS: henrique.santos@hurb.com
            

